### ISSUE TITLE
Update 1.0.1

### ISSUE THREAD

**Issue by jus61** [MezoPlays/Exile-MostWanted#1]
Can you Update to Exile 1.0.1

**Comment by Mezo** [comment]
There isn't a need to update, nothing has changed that effects this code.

**Comment by jus61** [comment]
THX

**Comment by jus61** [comment]
I can not connect to the server

Error :
`12:00:25 "ExileServer - Starting session for 'jus61' with ID 'TsVHvfnO'..."
12:00:25 Given magazine[acc_flashlight] not found)
12:00:25 Given magazine[acc_flashlight] not found)
12:00:25 "ExileServer - Dispatching hasPlayerRequest for session 'TsVHvfnO'..."
12:00:26 Error in expression <osition, [], 0, "CAN_COLLIDE"];
_player setDir _direction;
_player setPosATL _po>
12:00:26   Error position: <setDir _direction;
_player setPosATL _po>
12:00:26   Error setdir: Type Nothing, expected Object
12:00:26 File mpmissions\__cur_mp.Tanoa\MostWanted_Client\overwrites\ExileServer_object_player_database_load.sqf, line 22
12:00:26 Error in expression <osition, [], 0, "CAN_COLLIDE"];
_player setDir _direction;
_player setPosATL _po>
12:00:26   Error position: <setDir _direction;
_player setPosATL _po>
12:00:26   Error Generic error in expression
12:00:26 File mpmissions\__cur_mp.Tanoa\MostWanted_Client\overwrites\ExileServer_object_player_database_load.sqf, line 22
12:01:06 Client: Remote object 4:0 not found
12:01:06 Warning: Cleanup player - person 2:1100 not found
12:01:06 Warning: Cleanup player - person 2:1100 not found`

**Comment by Mezo** [comment]
Will have a look soon.
